
services:
  backend:
    build:
      context: ./Back-end  # Caminho correto para o diretório do backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend.env  # Referenciando o arquivo backend.env
    networks:
      - e_drive_network  # Adiciona à rede personalizada

  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - db.env  # Referenciando o arquivo db.env
    networks:
      - e_drive_network  # Adiciona à rede personalizada

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      # - "443:443"
      - "80:80"  # Mapear a porta 80 do container (Nginx) para a porta 80 do host
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - e_drive_network
    volumes:
      - ./certs:/etc/nginx/certs  # Adicione esta linha para montar os certificados

volumes:
  db_data: {}

networks:
  e_drive_network:
    driver: bridge  # Usando o driver de rede padrão para contêineres